---
- name: dns
  box: centos/7
  ip: 10.0.1.8
  mem: 4096
  cpu: 1
- name: master
  box: centos/7
  ip: 10.0.1.9
  mem: 4096
  cpu: 2
- name: minion01
  box: centos/7
  ip: 10.0.1.10
  mem: 8192
  cpu: 2
- name: minion02
  box: centos/7
  ip: 10.0.1.11
  mem: 8192
  cpu: 2
- name: minion03
  box: centos/7
  ip: 10.0.1.12
  mem: 8192
  cpu: 2
- name: minion04
  box: centos/7
  ip: 10.0.1.13
  mem: 8192
  cpu: 2
- name: monitor
  box: centos/7
  ip: 10.0.1.14
  mem: 4096
  cpu: 2
